# Generated by Django 4.0.5 on 2022-06-13 22:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AddField(
            model_name='post',
            name='Created_date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='post',
            name='Published_date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='post',
            name='Text',
            field=models.TextField(default='Text', max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='Title',
            field=models.CharField(default='Title', max_length=200),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
